### ISSUE TITLE
Wrong simulation references in GOF plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Pediatric_Qualification_Package_GFR_Ontogeny#19]
* All those simulation are in "Vancomycin", not in "Vancomycin-Pediatrics". 
* The first simulation is also wrongly named.
* Why is the GOF-section duplicated instead of using "predictedVsObserved|residualsOverTime" as plot type?

![grafik](https://user-images.githubusercontent.com/25061876/137108633-3dd01cc5-3086-4aa8-9c1c-f5178d1078f4.png)

![grafik](https://user-images.githubusercontent.com/25061876/137108261-6951bb49-6544-407d-bf35-026fc71d2ba2.png)
![grafik](https://user-images.githubusercontent.com/25061876/137108891-69fdfc48-7032-454c-94ea-8477c70924ea.png)

**Comment by Incei** [comment]
> * All those simulation are in "Vancomycin", not in "Vancomycin-Pediatrics".
> * The first simulation is also wrongly named.
> * Why is the GOF-section duplicated instead of using "predictedVsObserved|residualsOverTime" as plot type?
> 
> ![grafik](https://user-images.githubusercontent.com/25061876/137108633-3dd01cc5-3086-4aa8-9c1c-f5178d1078f4.png)
> 
> ![grafik](https://user-images.githubusercontent.com/25061876/137108261-6951bb49-6544-407d-bf35-026fc71d2ba2.png) ![grafik](https://user-images.githubusercontent.com/25061876/137108891-69fdfc48-7032-454c-94ea-8477c70924ea.png)

Hi @Yuri05 in my last pullrequest, the GOF plots are taken out as they belong to the adult model. Did you use the latest qualification plan?
